import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"
import { dark } from "@clerk/themes";
import { cn } from "@/lib/utils";
 

const fontSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],

});

{/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/}

export const metadata: Metadata = {
  title: "Project MEDIX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    
    <html lang="en" className="dark" style={{ colorScheme: "dark" }} suppressHydrationWarning>
      {/*<body className={`${plusJakartaSans.variable}`}> */}
      <body
        className={cn(
          "min-h-screen bg-dark-300 font-sans antialiased", //bg-dark-300
          fontSans.variable
        )}
      >
        <ThemeProvider 
        attribute="class" 
        defaultTheme="dark" 
        enableSystem={false}
        disableTransitionOnChange
        >
        {children}
        <Toaster richColors position='top-center' />
        </ThemeProvider>
      </body>
    </html>

    </ClerkProvider>
    
  );
}
